btnholaravel/routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Models\Warehouse;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'user',['middleware'=>['auth','check:1,2,3']]],function(){
    Route::get('export', [UserController::class,'export'])->name('export');
    Route::get('Product/{product}', [ProductController::class,'list'])->name('product.list');
    Route::get('sidebar', [UserController::class,'list'])->name('sidebar');
    Route::get('export_type', [TypeController::class,'export'])->name('type_export');
});

Route::group(['middleware'=>['auth','role:0']],function(){
    Route::post('sendMail/{user}' ,[UserController::class,'sendMail'])->name('sendMail');
    Route::resource('admin', UserController::class);
    Route::resource('warehouse', WarehouseController::class)->names('warehouse');
    Route::resource('type', TypeController::class)->names('type');
    Route::resource('product', ProductController::class)->names('product');
    
});

btnholaravel/app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Exports\TypeExport;
use App\Http\Requests\TypeRequest;
use App\Models\Product;
use App\Models\Type;
use App\Models\Warehouse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Maatwebsite\Excel\Facades\Excel;

class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $warehouses = Warehouse::all();
        $products = Product::with('types')->get();
        return view('types.index', compact('products','warehouses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $warehouses = Warehouse::all();
        $products = Product::all();
        return view('types.updateorcreate', compact('products','warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TypeRequest $request)
    {
        $warehouseid=Product::where('id',$request->product_id)->first()->warehouse_id;
        $types = Type::find($request->id);
        $soluong = $request->amount;
        if ($request->get('type_date') == 'Xuất') {
            $soluong = ($types->amount - $request->amount);
        }
        Type::updateOrCreate(
            ['id' => $request->id],
            [
                'name' => $request->name,
                'product_id' => $request->product_id,
                'type_date' => 'Nhập',
                'amount' => $soluong,
                'create_at' => $request->create_at
            ] 
        );
        return redirect()->route('product.list',$warehouseid);

       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function show(Type $type)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function edit(Type $type)
    {
        $warehouses = Warehouse::all();
        $products = Product::all();
        return view('types.edit', compact('products', 'type','warehouses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function update(TypeRequest $request, Type $type)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Type  $type
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $delete = Type::find($id);
        $delete->delete();
        return redirect()->back();
    }
    public function export()
    {
        return Excel::download(new TypeExport, 'Types.xlsx');
    }
}

btnholaravel/resources/views/types/detail.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>San pham</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="p-2 bd-highlight"><a href="{{ route('type.create') }}" class="btn btn-success">Add</a></div>
            <div class="p-2 bd-highlight">
                <form action="{{ route('type_export') }}" method="GET">
                    @csrf
                    <button class="btn btn-info" style="text-decoration: none; color: #ffff;" type="submit"
                        name="export_exel">Export excel</button>
                </form>
            </div>
            <table id="example2" class="table table-bordered table-hover">
                <thead>
                    @php
                        $i = 1;
                    @endphp
                    <tr>
                        <th>STT</th>
                        <th>Tên sản phẩm</th>
                        <th>Loại sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Loại</th>
                        <th>Ngày</th>
                        <th style="width:20px;"></th>
                        <th style="width:20px;"></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($products as $product)
                        @foreach ($product->types as $type)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $type->name }}</td>
                                <td>{{ $product->product_name }}</td>
                                <td>{{ $type->amount }}</td>
                                <td>{{ $type->type_date }}</td>
                                <td>{{ $type->create_at }}</td>
                                <td>
                                    <form action="{{ route('type.destroy', $type->id) }}"method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-warning">Xóa</button>
                                    </form>

                                </td>
                                <td><a class="btn btn-danger" href="{{ route('type.edit', $type->id) }}">Sửa</a></td>

                            </tr>
                        @endforeach
                    @endforeach



            </table>
        </div>
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/types/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{route('type.store',$type->id)}}" method="POST">
            @csrf
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" value="{{$type->name}}" name="name">
                <input type="text" hidden class="form-control" value="{{$type->id}}" name="id">
                @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>

            <div class="w-50 ml-5 pt-2 cart 6 table table-hover"> <label>Kiểu:</label><br>
                <select id="" name="type_date" class="form-select form-control  form-select-sm">

                    <option @selected($type->type_date == 'Nhập') value="Nhập">Nhập</option>
                    <option @selected($type->type_date == 'Xuất') value="Xuất">Xuất</option>

                </select>
                @error('type_date')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Số lượng</label>
                <input type="text" class="form-control" value="{{$type->amount}} "name="amount" >
                @error('amount')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Ngày</label>
                <input type="datetime" class="form-control" value="{{$type->create_at}}" name="create_at">
                @error('create_at')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="cars">Kho:</label><br>
                <select id="agileinfo-nav_search" name="product_id" class="form-control  form-select form-select-lg mb-3">
                    @foreach ($products as $product)
                        <option @selected($product->id == $type->product_id) value="{{ $product->id }}">{{ $product->product_name }}
                        </option>
                    @endforeach
                </select>
                @error('product_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
            </div>
            <button type="submit" name="edit" class="w-50 ml-5 pt-2  btn btn-primary">Submit</button>
        </form>
        <!-- /.card-header -->
        <div class="card-body">

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/types/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="p-2 bd-highlight"><a href="{{ route('type.create') }}" class="btn btn-success">Add</a></div>
            <div class="p-2 bd-highlight">
                <form action="{{ route('type_export') }}" method="GET">
                    @csrf
                    <button class="btn btn-info" style="text-decoration: none; color: #ffff;" type="submit"
                        name="export_exel">Export excel</button>
                </form>
            </div>
            <table id="example2" class="table table-bordered table-hover">
                <thead>
                    @php
                        $i = 1;
                    @endphp
                    <tr>
                        <th>STT</th>
                        <th>Tên sản phẩm</th>
                        <th>Loại sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Loại</th>
                        <th>Ngày</th>
                        <th style="width:20px;"></th>
                        <th style="width:20px;"></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($products as $product)
                        @foreach ($product->types as $type)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $type->name }}</td>
                                <td>{{ $product->product_name }}</td>
                                <td>{{ $type->amount }}</td>
                                <td>{{ $type->type_date }}</td>
                                <td>{{ $type->create_at }}</td>
                                <td>
                                    <form action="{{ route('type.destroy', $type->id) }}"method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-warning">Xóa</button>
                                    </form>

                                </td>
                                <td><a class="btn btn-danger" href="{{ route('type.edit', $type->id) }}">Sửa</a> </td>

                            </tr>
                        @endforeach
                    @endforeach



            </table>
        </div>
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/types/updateorcreate.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{ route('type.store') }}" method="POST">
            @csrf
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" name="name">
                @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Số lượng</label>
                <input type="number" class="form-control" name="amount">
                @error('amount')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover"> <label>Kiểu:</label><br>
                <select id="" name="type_date" class="form-select form-select-sm form-control">
                    <option value="">----Chọn Kiểu----</option>

                    <option value="Nhập">Nhập</option>
                    <option value="Xuất">Xuất</option>

                </select>
                @error('type_date')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Ngày</label>
                <input type="date" class="form-control" name="create_at">
                @error('create_at')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="w-50 ml-5 pt-2 cart 6 table table-hover"> <label for="cars">Loại sản phẩm:</label><br>

                <select id="agileinfo-nav_search" name="product_id" class="form-select form-select-lg mb-3 form-control">
                    <option value="">----Chọn loại sản phẩm---- </option>
                    @foreach ($products as $product)
                        <option value="{{ $product->id }}">{{ $product->product_name }}</option>
                    @endforeach
                </select>
                @error('product_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <button type="submit" class="ml-5 btn btn-primary">Submit</button>
        </form>
        <!-- /.card-header -->
        <div class="card-body">

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop