btnholaravel/routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Models\Warehouse;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'user',['middleware'=>['auth','check:1,2,3']]],function(){
    Route::get('export', [UserController::class,'export'])->name('export');
    Route::get('Product/{product}', [ProductController::class,'list'])->name('product.list');
    Route::get('sidebar', [UserController::class,'list'])->name('sidebar');
    Route::get('export_type', [TypeController::class,'export'])->name('type_export');
});

Route::group(['middleware'=>['auth','role:0']],function(){
    Route::post('sendMail/{user}' ,[UserController::class,'sendMail'])->name('sendMail');
    Route::resource('admin', UserController::class);
    Route::resource('warehouse', WarehouseController::class)->names('warehouse');
    Route::resource('type', TypeController::class)->names('type');
    Route::resource('product', ProductController::class)->names('product');
    
});

btnholaravel/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'role',
        'first_login',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function warehouse(){
        return $this->hasOne(Warehouse::class,'id','role');
    }
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
    
}

btnholaravel/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use app\Exports\UserExel;
use App\Exports\UsersExport;
use App\Models\Product;
use App\Models\Warehouse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Maatwebsite\Excel\Facades\Excel;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('warehouse')->get();
        $warehouses=Warehouse::all();
        return view('users.index', compact('users','warehouses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $warehouses = Warehouse::all();
        return view('users.create', compact('warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        User::Create($request->all());
        return redirect()->route('admin.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, User $user)
    {
        $request->validate([
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8',
        ]);
        $user = User::find($id);
        User::find($request->id)->update(
            [
                'first_login' => 0,
                'username' => $user->username,
                'email' => $request->email,
                'password' => $request->password,
            ]
        );
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('admin.index');
    }
    public function sendMail(Request $request,$user)
    {
        $user = User::where('username', $request->name)->first();
        $password = substr(md5(rand(1, 99999)), 0, 8);
       
        User::find($user->id)->update(
            [
                'first_login'=>1,
                'password'=>$password,
            ]
        );
        Mail::send(
            'users.email',
            compact(['user', 'password']),
            function ($message) use ($user) {
                $message->to($user->email, $user->name);
                $message->subject('Reset mật khẩu');
            }
        );
        return redirect()->route('admin.index');
    }
    public function export()
    {
        return Excel::download(new UsersExport, 'users.xlsx');
    }
    public function list()
    {
        $products=Product::all();
        $warehouses=Warehouse::all();
        return view('vendor.adminlte.sidebar.left-sidebar',compact('warehouses','products'));

    }
}

btnholaravel/resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{ route('admin.store') }}" method="POST">
            @csrf
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">username</label>
                <input type="text" class="form-control" name="username">
                @error('username')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Password</label>
                <input type="text" class="form-control" name="password">
                @error('password')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="cars">Chức vụ</label>
                <select id="agileinfo-nav_search" name="role" class="border form-control" >
                    <option>----Chọn----</option>
                   @foreach ($warehouses as $warehouse) 
                    <option value="{{$warehouse->id}}">{{$warehouse->name}}</option>
                    @endforeach
                </select>
                @error('role')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            
            <button type="submit" class="ml-5 btn btn-primary">Submit</button>
        </form>
     
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/users/email.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Yêu cầu thay đổi mật khẩu</title>
</head>
<body>
    <div>
        Chào bạn {{ $user->username }} Password của bạn là: {{$password}} 
        <a href="{{ route('login') }}"></a>
    </div>
</body>
</html>

btnholaravel/resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>User Manager</h1>
@stop

@section('content')
    <div class="card">

        <!-- /.card-header -->
        <div class="card-body">
            <div class="p-2 bd-highlight"><a class="btn btn-success" style="text-decoration: none; color: #ffff;"
                    href="{{ route('admin.create') }}">Add</a></div>
            <div class="p-2 bd-highlight">
                <form action="{{route('export')}}" method="Get">
                    @csrf
                    <button type="submit" class="btn btn-info" name="export_exel">Export excel</button>
                </form>
            </div>

            <table id="example2" class="table table-bordered table-hover">
                <tr>
                    @php $i = 0; @endphp
                    <th>STT</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Chức vụ</th>
                    <th style="width:20px;">Xóa</th>
                    
                </tr>  
                @foreach ($users as $user)
                    <tr @if ($loop->first) hidden @endif>
                        <td>{{ $i++ }}</td>
                        <td>{{ $user->username }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->warehouse->name ?? 'admin' }}</td>
                        <td>
                            <form action="{{ route('admin.destroy', $user->id) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" type="submit">Xóa</button>
                            </form>
                        </td>
                        
                        <td>
                            <form action="{{ route('sendMail',$user->username) }}" method="POST">
                                @csrf
                                <input type="text" hidden class="check" name="check" value="{{ $user->email }}">
                                <input type="hidden" name="name" value="{{ $user->username }}">
                                <button type="submit" class=" btn btn-secondary">Reset password</button>
                            </form>
                        </td>

                    </tr>
                @endforeach


            </table>

        </div>
        <!-- /.card-body -->
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/users/update.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
    </script>
    <title>Document</title>

</head>

<body>
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh ;">
        <form  action="{{route('admin.update',$user->id) }}" class="border shadow p-3 rounded" method="POST"
            style="width:400px">
            @method('PUT')
            @csrf
            <h1 class="text-center p3" style="font-size:15px ;">CHANGE PASSWORD</h1>
            <div class="mb-3">
                <label for="email">Email</label>
                <input type="email" id="email" class="form-control" id="email" name="email">
                @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="password">Password</label>
                <input type="password" id="password" class="form-control" id="password" name="password">
                @error('password')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="mb-3">
                <label for="confirm">Confirm password</label>
                <input type="confirm" id="confirm_password" class="form-control" id="confirm"
                    name="password_confirmation">
                @error('password_confirmation')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <input type="id" hidden value="{{ $user->id }}" class="form-control" id="id" name="id">



            <button type="submit" name="forgot" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>

</html>