btnholaravel/routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Models\Warehouse;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'user',['middleware'=>['auth','check:1,2,3']]],function(){
    Route::get('export', [UserController::class,'export'])->name('export');
    Route::get('Product/{product}', [ProductController::class,'list'])->name('product.list');
    Route::get('sidebar', [UserController::class,'list'])->name('sidebar');
    Route::get('export_type', [TypeController::class,'export'])->name('type_export');
});

Route::group(['middleware'=>['auth','role:0']],function(){
    Route::post('sendMail/{user}' ,[UserController::class,'sendMail'])->name('sendMail');
    Route::resource('admin', UserController::class);
    Route::resource('warehouse', WarehouseController::class)->names('warehouse');
    Route::resource('type', TypeController::class)->names('type');
    Route::resource('product', ProductController::class)->names('product');
    
});

btnholaravel/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Type;
use App\Models\Warehouse;

class Product extends Model
{
    use HasFactory;
    protected $fillable=[
        'product_name',
        'warehouse_id',
    ];
    public function types()
    {
        return $this->hasMany(Type::class,'product_id','id');
    }
    public function warehouse(){
        return $this->belongsTo(warehouse::class,'warehouse_id','id');
    }
}

btnholaravel/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Models\Type;
use App\Models\Warehouse;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $warehouses = Warehouse::with('products')->get();
        return view('products.index')->with(
            [
                'warehouses' => $warehouses
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $warehouses = Warehouse::all();
        return view('products.updateorcreate', compact('warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {

        Product::updateOrCreate(
            ['id' => $request->id],
            [
                'product_name' => $request->name,
                'warehouse_id' => $request->warehouse_id

            ]
        );
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $warehouses = Warehouse::all();
        return view('products.edit', compact('warehouses', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Product::find($id);
        $delete->delete();
        return redirect()->route('product.index');
    }

    public function list($id)
    {
        $warehouses = Warehouse::all();
        $lists = Product::where('warehouse_id', $id)->with('types')->get();
        return view('types.detail')->with(
            [
                'products'=> $lists,
                'warehouses'=>$warehouses

            ]
        );
    }
}

btnholaravel/resources/views/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{route('product.store',$product->id)}}" method="POST">
            @csrf
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <input hidden type="text" name="id" value="{{$product->id}}">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" value="{{$product->product_name}}" name="name">
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover"> <label for="cars">Kho:</label>
                <select id="agileinfo-nav_search" name="warehouse_id" class="form-select form-select-lg mb-3 form-control"
                    required="">
                    <option value="">----Chọn kho----</option>
                    @foreach ($warehouses as $warehouse)
                        <option @selected($warehouse->id==$product->warehouse_id) value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>
                    @endforeach


                </select>
            </div>

            <button type="submit" class="ml-5 btn btn-primary">Submit</button>
        </form>
        <!-- /.card-header -->
        <div class="card-body">

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">

        <!-- /.card-header -->
        <div class="card-body">
            <div class="p-2 bd-highlight">
                <a class="btn btn-success" href="{{ route('product.create') }}">Add</a>
            </div>
            <table id="example2" class="table table-bordered table-hover">
                <thead>
                    @php
                        $i = 1;
                    @endphp
                    <tr>
                        <th>STT</th>
                        <th>Name</th>
                        <th>Kho</th>
                        <th style="width:20px;"> </th>
                        <th style="width:20px;"> </th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($warehouses as $warehouse)
                        @foreach ($warehouse->products as $product)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $product->product_name }}</td>
                                <td>{{ $warehouse->name }}</td>
                                <td><a class="btn btn-danger" href="{{route('product.edit',$product->id)}}">Sửa</a> </td>
                                <td>
                                    <form action="{{ route('product.destroy', $product->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-warning">Xóa</button>
                                </td>
                                </form>

                            </tr>
                        @endforeach
                    @endforeach
            </table>
        </div>
        <!-- /.card-body -->
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/products/updateorcreate.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="card">
        <form action="{{route('product.store')}}" method="POST">
            @csrf
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" name="name">
                @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>
            <div class="w-50 ml-5 pt-2 cart 6 table table-hover"> <label for="cars">Kho:</label>
                <select id="agileinfo-nav_search" name="warehouse_id" class="form-select form-select-lg mb-3 form-control"
                    >
                    <option value="">----Chọn kho----</option>
                    @foreach ($warehouses as $warehouse)
                        <option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>
                    @endforeach


                </select>
                @error('warehouse_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            </div>

            <button type="submit" class="ml-5 btn btn-primary">Submit</button>
        </form>
        <!-- /.card-header -->
        <div class="card-body">

        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop