btnholaravel/routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use App\Models\Warehouse;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix'=>'user',['middleware'=>['auth','check:1,2,3']]],function(){
    Route::get('export', [UserController::class,'export'])->name('export');
    Route::get('Product/{product}', [ProductController::class,'list'])->name('product.list');
    Route::get('sidebar', [UserController::class,'list'])->name('sidebar');
    Route::get('export_type', [TypeController::class,'export'])->name('type_export');
});

Route::group(['middleware'=>['auth','role:0']],function(){
    Route::post('sendMail/{user}' ,[UserController::class,'sendMail'])->name('sendMail');
    Route::resource('admin', UserController::class);
    Route::resource('warehouse', WarehouseController::class)->names('warehouse');
    Route::resource('type', TypeController::class)->names('type');
    Route::resource('product', ProductController::class)->names('product');
    
});

btnholaravel/resources/views/warehouses/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Quản lý kho hàng</h1>
@stop

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">CREATE OR UPDATE</h3>
        </div>

        <div class="card-body">
            <form action="{{ route('warehouse.store', $warehouse->id) }}" method="POST">

                @csrf
                <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                    <input class="form-control" type="text" value="{{ $warehouse->id }}" hidden name="id">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" value="{{ $warehouse->name }}" name="name">
                    @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="ml-5 btn btn-primary">Submit</button>
            </form>
        </div>

        <div class="card-footer clearfix">

        </div>
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/warehouses/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Quản lý kho hàng</h1>
@stop

@section('content')

    <div class="card">

        <div class="card-body">
            <a class="btn btn-primary" href="{{ route('warehouse.create') }}">Add</a>
            <table class="table table-bordered">
                
                <thead>
                    <tr>
                        <th style="width: 10px">STT</th>
                        <th>Name</th>
                        <th style="width: 40px"></th>
                        <th style="width: 40px"></th>
                    </tr>
                </thead>
                <tbody>
                    @php
                     $stt=1;   
                    @endphp
                    @foreach ($warehouses as $warehouse)
                        <tr>
                            <td>{{$stt++}}</td>
                            <td>{{$warehouse->name}}</td>

                            <td><a class="btn btn-primary" href="{{ route('warehouse.edit', $warehouse->id) }}">Edit</a></td>
                            <td><form  action="{{route('warehouse.destroy',$warehouse->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger" >Delete</button>
                            </form></td>
                        </tr>
                    @endforeach


                </tbody>
            </table>
        </div>

        <div class="card-footer clearfix">

        </div>
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop

btnholaravel/resources/views/warehouses/updateorcreate.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Quản lý kho hàng</h1>
@stop

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">CREATE OR UPDATE</h3>
        </div>

        <div class="card-body">
            <form action="{{ route('warehouse.store') }}" method="POST">
                @csrf
                <div class="w-50 ml-5 pt-2 cart 6 table table-hover">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" name="name">
                    @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="ml-5 btn btn-primary">Submit</button>
            </form>
        </div>

        <div class="card-footer clearfix">

        </div>
    </div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        console.log('Hi!');
    </script>
@stop